version: "3.8"

services:
    articles-bdd:
        build: ./articles-db
        image: articles-bdd:v1
        container_name: articles-bdd
        networks:
            - articles-network
        volumes:
            - articles-bdd-data:/var/lib/mysql
    
    articles-back:
        build: ./articles-back
        image: articles-back:v1
        container_name: articles-back
        ports:
            - "8081:8080"
        depends_on:
            - articles-bdd
        networks:
            - articles-network
            
    articles-front:
        build: ./articles-front
        image: articles-front:v3
        container_name: articles-front
        depends_on:
            - articles-back
        ports:
            - "9000:80"
        networks:
            - articles-network

networks:
    articles-network:

volumes:
    articles-bdd-data: